import type { Metadata } from "next";
import { M_PLUS_1p } from "next/font/google";
import "./globals.css";
import {NextFont} from "next/dist/compiled/@next/font";

const mPlus1p :NextFont = M_PLUS_1p({
  weight: '700',
  preload: false
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mPlus1p.className}>{children}</body>
    </html>
  );
}
